USE LMS;
SET SQL_SAFE_UPDATES = 0;



    
INSERT INTO books
 (`ISBN10`,
  `ISBN13`,
  `TITLE`,
  
  `COVER`,
  `PUBLISHER`,
  `PAGES`) 
SELECT `ISBN10`,`ISBN13`,`TITLE`,`COVER`,`PUBLISHER`,`PAGE` FROM `BOOKS_DATA`;

UPDATE BOOKS
SET BOOKS.TOTAL_COPIES = 3, BOOKS.COPIES_BORROWED = 0;


INSERT INTO BORROWER
(   
	`CARD_ID`,
    `SSN`,
	`FNAME` ,
    `LNAME` ,
    `BNAME` ,
    `EMAIL` ,
    `ADDRESS`,
    `CITY` ,
    `STATE` ,
    `FULL_ADDRESS`,
    `PHONE`  
   
    )
SELECT  `BORROWER_ID` AS CARD_ID,`SSN`,
	`F_NAME` ,
    `L_NAME` ,
    CONCAT(`F_NAME` , ' '  , `L_NAME`) AS BNAME ,
    `EMAIL` ,
    `ADDRESS`,
    `CITY` ,
    `STATE` ,
     CONCAT(`ADDRESS` , ' ', `CITY`,' ',  `STATE`) AS FULL_ADDRESS,
    `PHONE`  
    FROM BORROWER_DATA;
    

INSERT INTO AUTHORS (NAME)
SELECT NAME FROM AUTHORS_DATA;





 
 INSERT INTO BOOK_AUTHORS
(	AUTHOR_ID,
	ISBN10,
	ISBN13
)
SELECT 
	   AUTHORS.AUTHOR_ID,
       BOOKS_DATA.ISBN10,
	   BOOKS_DATA.ISBN13 

	FROM BOOKS_DATA
	INNER JOIN AUTHORS
	ON FIND_IN_SET(LOWER(AUTHORS.NAME), LOWER(BOOKS_DATA.AUTHOR));

    
   INSERT INTO BOOK_AUTHOR
(NAME,
AUTHOR_ID,
BOOKAUTHOR_ID,
ISBN13,
ISBN10)
SELECT AUTHORS.NAME,AUTHORS.AUTHOR_ID,BOOK_AUTHORS.BOOKAUTHOR_ID,BOOK_AUTHORS.ISBN13,BOOK_AUTHORS.ISBN10 FROM BOOK_AUTHORS 
INNER JOIN AUTHORS 
 WHERE BOOK_AUTHORS.AUTHOR_ID = AUTHORS.AUTHOR_ID;

