Drop DATABASE IF EXISTS LMS;
CREATE DATABASE LMS;
USE LMS;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(	ISBN10 VARCHAR(10) NOT NULL,
	ISBN13 VARCHAR(13) NOT NULL,
	TITLE TEXT,    
    COVER TEXT,
    PUBLISHER TEXT,
    PAGES VARCHAR(255),
    TOTAL_COPIES INT,
    COPIES_BORROWED INT,
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    
    CONSTRAINT pk_Book PRIMARY KEY (ISBN13)
);

DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS
(	
	/*AUTHOR_KEY INT NOT NULL,*/
	AUTHOR_ID BIGINT AUTO_INCREMENT NOT NULL,
	NAME TEXT,
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    
    CONSTRAINT pk_Authors PRIMARY KEY (AUTHOR_ID)
   
);

DROP TABLE IF EXISTS BOOK_AUTHORS;

CREATE TABLE BOOK_AUTHORS
(	

	BOOKAUTHOR_ID BIGINT AUTO_INCREMENT NOT NULL,
	AUTHOR_ID BIGINT NOT NULL,
    ISBN10 VARCHAR(10) NOT NULL,
	ISBN13 VARCHAR(13) NOT NULL,
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    
    CONSTRAINT pk_Book_Authors PRIMARY KEY (BOOKAUTHOR_ID),
    CONSTRAINT fk_BookAuthors_Book FOREIGN KEY (ISBN13) references BOOKS(ISBN13),
     CONSTRAINT fk_BookAuthors_Authors FOREIGN KEY (AUTHOR_ID) references AUTHORS(AUTHOR_ID) 
);



DROP TABLE IF EXISTS BORROWER;

CREATE TABLE BORROWER
(	
    /*BORROWER_ID INT  NULL, */
	CARD_ID INT AUTO_INCREMENT  NOT NULL  ,
	SSN     VARCHAR(15) NOT NULL,
	FNAME TEXT,
    LNAME TEXT,
    BNAME   TEXT,
    EMAIL TEXT,
    ADDRESS TEXT,
    CITY TEXT,
    STATE TEXT,
    FULL_ADDRESS TEXT,
    PHONE   VARCHAR(20),
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME,
    
    CONSTRAINT pk_Borrower PRIMARY KEY (CARD_ID)
);

DROP TABLE IF EXISTS BOOK_LOANS;

CREATE TABLE BOOK_LOANS
(	
	LOAN_ID INT AUTO_INCREMENT NOT NULL,
    ISBN13 VARCHAR(13) NOT NULL,
    CARD_ID INT NOT NULL ,
    DATE_IN DATETIME,
	DATE_OUT DATETIME,
    DUE_DATE DATETIME,
    
    CONSTRAINT pk_Book_Loans PRIMARY KEY (LOAN_ID),
	CONSTRAINT fk_BookLoans_Borrower FOREIGN KEY (CARD_ID) references BORROWER(CARD_ID),
    CONSTRAINT fk_BookLoans_Book FOREIGN KEY (ISBN13) references BOOKS(ISBN13)
    
);

DROP TABLE IF EXISTS FINES;

CREATE TABLE FINES
(	
	FINE_ID INT AUTO_INCREMENT NOT NULL,
	LOAN_ID INT NOT NULL,
    FINE_AMOUNT DECIMAL(15,2),
    PAID  BOOL DEFAULT 0,
    
    CONSTRAINT pk_Fines PRIMARY KEY (FINE_ID),
	CONSTRAINT fk_Fines_BookLoans FOREIGN KEY (LOAN_ID) references BOOK_LOANS(LOAN_ID)
);


